import React from "react";
import Image from "next/image";
import Link from "next/link";

const PerceptDiffBlog = () => {
  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">
        Percept-Diff: High-Fidelity IHC Image Generation for HER2 Breast Cancer
      </h1>

      <p className="mb-6 text-lg">
        Breast cancer, particularly the HER2-positive variant, is one of the most aggressive forms of cancer. Early detection is crucial, but standard testing methods are often expensive and inaccessible. <strong>Percept-Diff</strong> offers a deep-learning-based solution that generates high-fidelity Immunohistochemical (IHC) images, preserving patient privacy while augmenting scarce medical datasets.
      </p>

      <h2 className="text-2xl font-semibold mb-3">Motivation</h2>
      <p className="mb-6">
        Deep learning models for medical imaging require large datasets, which are often limited due to patient privacy concerns. Percept-Diff leverages Stable Diffusion models to synthetically generate realistic IHC images for HER2-positive breast cancer at different stages (0+, 1+, 3+), enabling research and training of diagnostic models without exposing sensitive data.
      </p>

      <h2 className="text-2xl font-semibold mb-3">Proposed Method: Percept-Diff</h2>
      <p className="mb-4">
        Percept-Diff combines Stable Diffusion with perceptual loss using a pre-trained VGG19 network. L1 loss, instance loss, and prior loss are incorporated to reduce noise and improve image quality. The diffusion process is performed in latent space via variational autoencoders (VAE) with KL divergence.
      </p>
      <Image
        src="/percept-diff/method.png"
        alt="Percept-Diff Architecture"
        width={800}
        height={500}
        className="mb-6 rounded-lg shadow-md"
      />

      <h2 className="text-2xl font-semibold mb-3">Performance Evaluation</h2>
      <p className="mb-4">
        Three key metrics were used to evaluate the generated images:
      </p>
      <ul className="list-disc list-inside mb-6">
        <li><strong>CLIP Score:</strong> Measures alignment between images and text prompts.</li>
        <li><strong>FID (Frechet Inception Distance):</strong> Evaluates similarity of generated images to real images; lower is better.</li>
        <li><strong>KID (Kernel Inception Distance):</strong> A robust metric similar to FID, especially with small datasets.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-3">Results</h2>
      <table className="w-full mb-6 border border-gray-300 text-left">
        <thead className="bg-gray-100">
          <tr>
            <th className="border px-4 py-2">Model</th>
            <th className="border px-4 py-2">CLIP Score</th>
            <th className="border px-4 py-2">FID</th>
            <th className="border px-4 py-2">KID</th>
          </tr>
        </thead>
        <tbody>
          <tr><td className="border px-4 py-2">Stable Diffusion-2</td><td className="border px-4 py-2">25.41</td><td className="border px-4 py-2">330.62</td><td className="border px-4 py-2">0.0022</td></tr>
          <tr><td className="border px-4 py-2">Stable Diffusion-2-base</td><td className="border px-4 py-2">25.44</td><td className="border px-4 py-2">313.23</td><td className="border px-4 py-2">0.0009</td></tr>
          <tr><td className="border px-4 py-2">Realistic Vision-V51 (fine-tuned)</td><td className="border px-4 py-2">31</td><td className="border px-4 py-2">239</td><td className="border px-4 py-2">0.0099</td></tr>
          <tr className="font-bold"><td className="border px-4 py-2">Percept-Diff</td><td className="border px-4 py-2">35</td><td className="border px-4 py-2">230</td><td className="border px-4 py-2">0.0101</td></tr>
        </tbody>
      </table>

      <h2 className="text-2xl font-semibold mb-3">Sample Outputs</h2>
      <p className="mb-4">Here are some sample IHC images generated by Percept-Diff:</p>
      <Image
        src="/percept-diff/sample-output.png"
        alt="Sample Generated IHC Images"
        width={800}
        height={500}
        className="mb-6 rounded-lg shadow-md"
      />

      <h2 className="text-2xl font-semibold mb-3">Conclusion</h2>
      <p className="mb-6">
        Percept-Diff generates high-fidelity IHC images for HER2-positive breast cancer with minimal real data, preserving patient privacy. This method outperforms other state-of-the-art diffusion models and can help researchers overcome data scarcity while contributing to early detection and treatment of breast cancer.
      </p>

      <p className="mb-6">
        For full technical details, see the complete paper:{" "}
        <Link
          href="https://ieeexplore.ieee.org/document/10824425"
          target="_blank"
          className="text-blue-600 underline"
        >
          Full Paper on IEEE Xplore
        </Link>
      </p>
    </div>
  );
};

export default PerceptDiffBlog;
